manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dsifry
      url-base: https://github.com/dsifry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/manifest.yml
    - name: nice-view-mod
      remote: dsifry
      revision: main
  self:
    path: config